/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package jusmartlabsystem.FormLogin;
import jusmartlabsystem.AdminDash.frmAdminDashboard2;
import jusmartlabsystem.SuperAdminDash.frmSuperAdminDashboard2;
import jusmartlabsystem.FormDB.DatabaseHelper;
import java.sql.*;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import java.util.*;
import java.io.*;





/**
 *
 * @author PC
 */
public class frmChangePass extends javax.swing.JFrame {

    /**
     * Creates new form frmLogin
     */
    public frmChangePass() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtAdminsRetypePassw = new javax.swing.JPasswordField();
        ExitBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        LoginBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtAdminsEmail = new javax.swing.JTextField();
        txtAdminsNewPassw = new javax.swing.JPasswordField();
        ChangeBtn = new javax.swing.JButton();
        ShowPassCheckBox = new javax.swing.JCheckBox();
        txtAdminsPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 102));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Retype Password : ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, -1, -1));

        txtAdminsRetypePassw.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jPanel2.add(txtAdminsRetypePassw, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 190, 30));

        ExitBtn.setBackground(new java.awt.Color(51, 153, 255));
        ExitBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        ExitBtn.setForeground(new java.awt.Color(255, 255, 255));
        ExitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jusmartlabsystem/Resources/closelatest(30).png"))); // NOI18N
        ExitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBtnActionPerformed(evt);
            }
        });
        jPanel2.add(ExitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 50, 40));

        jLabel5.setText("Old Password  : ");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        LoginBtn.setBackground(new java.awt.Color(51, 153, 255));
        LoginBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        LoginBtn.setForeground(new java.awt.Color(255, 255, 255));
        LoginBtn.setText("Login");
        LoginBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBtnActionPerformed(evt);
            }
        });
        jPanel2.add(LoginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 360, 42));

        jLabel7.setText("New Passsword  : ");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        jLabel9.setBackground(new java.awt.Color(51, 153, 255));
        jLabel9.setFont(new java.awt.Font("Cascadia Code", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 153, 255));
        jLabel9.setText("Change password ");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, -1, -1));

        jLabel6.setText("Enter Your  Email : ");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        txtAdminsEmail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        txtAdminsEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdminsEmailActionPerformed(evt);
            }
        });
        jPanel2.add(txtAdminsEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 190, 30));

        txtAdminsNewPassw.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jPanel2.add(txtAdminsNewPassw, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 190, 30));

        ChangeBtn.setBackground(new java.awt.Color(51, 153, 255));
        ChangeBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        ChangeBtn.setForeground(new java.awt.Color(255, 255, 255));
        ChangeBtn.setText("Change Password");
        ChangeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ChangeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeBtnActionPerformed(evt);
            }
        });
        jPanel2.add(ChangeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 360, 42));

        ShowPassCheckBox.setText("Show Password");
        ShowPassCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowPassCheckBoxActionPerformed(evt);
            }
        });
        jPanel2.add(ShowPassCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, -1, -1));

        txtAdminsPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jPanel2.add(txtAdminsPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 190, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBtnActionPerformed
              // TODO add your handling code here:
              System.exit(0);
    }//GEN-LAST:event_ExitBtnActionPerformed

    
        
    private void LoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBtnActionPerformed
             // TODO add your handling code here:
             
             frmLogin frmLogin = new frmLogin();
             frmLogin.setVisible(true);
             this.dispose();


 
             
             
             
             
             
             
    }//GEN-LAST:event_LoginBtnActionPerformed

    private void ChangeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeBtnActionPerformed
        // TODO add your handling code here:
        
           try {

        String email = txtAdminsEmail.getText().trim();
        String oldPass = txtAdminsPassword.getText().trim();
        String newPass = String.valueOf(txtAdminsNewPassw.getPassword());
        String rePass = String.valueOf(txtAdminsRetypePassw.getPassword());

        // Check empty fields
        if(email.isEmpty() || oldPass.isEmpty()
                || newPass.isEmpty() || rePass.isEmpty()) {

            JOptionPane.showMessageDialog(this,
                    "Please fill all fields");
            return;
        }

        // Check password match
        if(!newPass.equals(rePass)) {

            JOptionPane.showMessageDialog(this,
                    "New Password and Retype Password do not match");
            return;
        }

        Connection con = DatabaseHelper.getConnection();

        // Verify email and old password
        String checkSql =
                "SELECT * FROM admins WHERE Email=? AND Password=?";

        PreparedStatement pst =
                con.prepareStatement(checkSql);

        pst.setString(1, email);
        pst.setString(2, oldPass);

        ResultSet rs = pst.executeQuery();

        if(rs.next()) {

            // Update password
            String updateSql =
                    "UPDATE admins SET Password=? WHERE Email=?";

            PreparedStatement pst2 =
                    con.prepareStatement(updateSql);

            pst2.setString(1, newPass);
            pst2.setString(2, email);

            int updated = pst2.executeUpdate();

            if(updated > 0) {

                JOptionPane.showMessageDialog(this,
                        "Password Changed Successfully");

                txtAdminsEmail.setText("");
                txtAdminsPassword.setText("");
                txtAdminsNewPassw.setText("");
                txtAdminsRetypePassw.setText("");

            } else {

                JOptionPane.showMessageDialog(this,
                        "Password Change Failed");
            }

            pst2.close();

        } else {

            JOptionPane.showMessageDialog(this,
                    "Invalid Email or Old Password");
        }

        rs.close();
        pst.close();
        con.close();

    } catch(Exception e) {

        JOptionPane.showMessageDialog(this,
                e.getMessage());
    }
    }//GEN-LAST:event_ChangeBtnActionPerformed

    private void txtAdminsEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdminsEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdminsEmailActionPerformed

    private void ShowPassCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowPassCheckBoxActionPerformed
        // TODO add your handling code here:
        if(ShowPassCheckBox.isSelected()){

    txtAdminsPassword.setEchoChar((char)0);
    txtAdminsNewPassw.setEchoChar((char)0);
    txtAdminsRetypePassw.setEchoChar((char)0);

}else{

    txtAdminsPassword.setEchoChar('*');
    txtAdminsNewPassw.setEchoChar('*');
    txtAdminsRetypePassw.setEchoChar('*');
}
    }//GEN-LAST:event_ShowPassCheckBoxActionPerformed
    
   
       

        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new frmLogin().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChangeBtn;
    private javax.swing.JButton ExitBtn;
    private javax.swing.JButton LoginBtn;
    private javax.swing.JCheckBox ShowPassCheckBox;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtAdminsEmail;
    private javax.swing.JPasswordField txtAdminsNewPassw;
    private javax.swing.JPasswordField txtAdminsPassword;
    private javax.swing.JPasswordField txtAdminsRetypePassw;
    // End of variables declaration//GEN-END:variables
}
