/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package jusmartlabsystem.FormLogin;
import jusmartlabsystem.AdminDash.frmAdminDashboard2;
import jusmartlabsystem.SuperAdminDash.frmSuperAdminDashboard2;
import jusmartlabsystem.FormDB.DatabaseHelper;
import java.sql.*;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import java.util.*;
import java.io.*;





/**
 *
 * @author PC
 */
public class frmForgetPass extends javax.swing.JFrame {

    /**
     * Creates new form frmLogin
     */
    public frmForgetPass() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        txtAdminsQuest = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPasswordAmins = new javax.swing.JPasswordField();
        ExitBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        CheckingBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtAdminsEmail = new javax.swing.JTextField();
        txtAdminsAnsw = new javax.swing.JPasswordField();
        ForgetBtn = new javax.swing.JButton();
        LoginBtn1 = new javax.swing.JButton();
        ShowPassCheckBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 102));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtAdminsQuest.setEditable(false);
        txtAdminsQuest.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jPanel2.add(txtAdminsQuest, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 290, 30));

        jLabel3.setText("Password : ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, -1, -1));

        txtPasswordAmins.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jPanel2.add(txtPasswordAmins, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 290, 30));

        ExitBtn.setBackground(new java.awt.Color(51, 153, 255));
        ExitBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        ExitBtn.setForeground(new java.awt.Color(255, 255, 255));
        ExitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jusmartlabsystem/Resources/closelatest(30).png"))); // NOI18N
        ExitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBtnActionPerformed(evt);
            }
        });
        jPanel2.add(ExitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 50, 40));

        jLabel5.setText("Secret question  : ");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        CheckingBtn.setBackground(new java.awt.Color(51, 153, 255));
        CheckingBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CheckingBtn.setForeground(new java.awt.Color(255, 255, 255));
        CheckingBtn.setText("Checking");
        CheckingBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CheckingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckingBtnActionPerformed(evt);
            }
        });
        jPanel2.add(CheckingBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 90, 30));

        jLabel7.setText("Secret Answer : ");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        jLabel9.setBackground(new java.awt.Color(51, 153, 255));
        jLabel9.setFont(new java.awt.Font("Cascadia Code", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 51));
        jLabel9.setText("Forget password ");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, -1, -1));

        jLabel6.setText("Enter Your Email : ");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        txtAdminsEmail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jPanel2.add(txtAdminsEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 190, 30));

        txtAdminsAnsw.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jPanel2.add(txtAdminsAnsw, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 290, 30));

        ForgetBtn.setBackground(new java.awt.Color(51, 153, 255));
        ForgetBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        ForgetBtn.setForeground(new java.awt.Color(255, 255, 255));
        ForgetBtn.setText("Forget Password");
        ForgetBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ForgetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ForgetBtnActionPerformed(evt);
            }
        });
        jPanel2.add(ForgetBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 460, 42));

        LoginBtn1.setBackground(new java.awt.Color(51, 153, 255));
        LoginBtn1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        LoginBtn1.setForeground(new java.awt.Color(255, 255, 255));
        LoginBtn1.setText("Login");
        LoginBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LoginBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBtn1ActionPerformed(evt);
            }
        });
        jPanel2.add(LoginBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 460, 42));

        ShowPassCheckBox.setText("Show Password");
        ShowPassCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowPassCheckBoxActionPerformed(evt);
            }
        });
        jPanel2.add(ShowPassCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBtnActionPerformed
              // TODO add your handling code here:
              System.exit(0);
    }//GEN-LAST:event_ExitBtnActionPerformed

    
        
    private void CheckingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckingBtnActionPerformed
             // TODO add your handling code here:
             
             try {

    Connection con = DatabaseHelper.getConnection();

    String sql =
    "SELECT SecretQuestion FROM admins WHERE Email=?";

    PreparedStatement pst =
    con.prepareStatement(sql);

    pst.setString(1, txtAdminsEmail.getText().trim());

    ResultSet rs = pst.executeQuery();

    if(rs.next()){

        txtAdminsQuest.setText(
                rs.getString("SecretQuestion"));

    }else{

        JOptionPane.showMessageDialog(this,
                "Email Not Found");
    }

}
catch(Exception e){

    JOptionPane.showMessageDialog(this,e);
}
               
             
             
             
             
    }//GEN-LAST:event_CheckingBtnActionPerformed

    private void ForgetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ForgetBtnActionPerformed
        // TODO add your handling code here:
        try {

    String email =
            txtAdminsEmail.getText().trim();

    String answer =
            txtAdminsAnsw.getText().trim();

    Connection con =
            DatabaseHelper.getConnection();

    String sql =
    "SELECT Password FROM admins "
    + "WHERE Email=? "
    + "AND LOWER(SecretAnswer)=LOWER(?)";

    PreparedStatement pst =
    con.prepareStatement(sql);

    pst.setString(1,email);
    pst.setString(2,answer);

    ResultSet rs =
    pst.executeQuery();

    if(rs.next()){

        txtPasswordAmins.setText(
                rs.getString("Password"));

    }else{

        JOptionPane.showMessageDialog(this,
                "Wrong Secret Answer");
    }

}
catch(Exception e){

    JOptionPane.showMessageDialog(this,e);
}
    }//GEN-LAST:event_ForgetBtnActionPerformed

    private void LoginBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBtn1ActionPerformed
        // TODO add your handling code here:
           frmLogin frmLogin = new frmLogin();
           frmLogin.setVisible(true);
           this.dispose();
    }//GEN-LAST:event_LoginBtn1ActionPerformed

    private void ShowPassCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowPassCheckBoxActionPerformed
        // TODO add your handling code here:
        if(ShowPassCheckBox.isSelected()){

    txtPasswordAmins.setEchoChar((char)0);
    txtAdminsAnsw.setEchoChar((char)0);

}else{

    txtPasswordAmins.setEchoChar('*');
    txtAdminsAnsw.setEchoChar('*');
}
    }//GEN-LAST:event_ShowPassCheckBoxActionPerformed
    
   
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new frmLogin().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CheckingBtn;
    private javax.swing.JButton ExitBtn;
    private javax.swing.JButton ForgetBtn;
    private javax.swing.JButton LoginBtn1;
    private javax.swing.JCheckBox ShowPassCheckBox;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField txtAdminsAnsw;
    private javax.swing.JTextField txtAdminsEmail;
    private javax.swing.JTextField txtAdminsQuest;
    private javax.swing.JPasswordField txtPasswordAmins;
    // End of variables declaration//GEN-END:variables
}
