/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package jusmartlabsystem.FormLogin;
import jusmartlabsystem.AdminDash.frmAdminDashboard2;
import jusmartlabsystem.SuperAdminDash.frmSuperAdminDashboard2;
import jusmartlabsystem.FormDB.DatabaseHelper;
import java.sql.*;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import java.util.*;
import java.io.*;





/**
 *
 * @author PC
 */
public class frmLogin extends javax.swing.JFrame {

    /**
     * Creates new form frmLogin
     */
    public frmLogin() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        ExitBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        LoginBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cmbRoles = new javax.swing.JComboBox<>();
        ForgetPass = new javax.swing.JLabel();
        changePass = new javax.swing.JLabel();
        ShowPassCheckBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 102));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        jLabel1.setFont(new java.awt.Font("Cascadia Code", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Back ");

        jLabel6.setFont(new java.awt.Font("Cascadia Code", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Welcome ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(168, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(155, 155, 155))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jusmartlabsystem/Resources/lgn2.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        txtUserName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jPanel2.add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 190, 30));

        jLabel3.setText("Role : ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));

        txtPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jPanel2.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 190, 30));

        ExitBtn.setBackground(new java.awt.Color(51, 153, 255));
        ExitBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        ExitBtn.setForeground(new java.awt.Color(255, 255, 255));
        ExitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jusmartlabsystem/Resources/closelatest(30).png"))); // NOI18N
        ExitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBtnActionPerformed(evt);
            }
        });
        jPanel2.add(ExitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 50, 40));

        jLabel5.setText("Enter Your Email : ");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        LoginBtn.setBackground(new java.awt.Color(51, 153, 255));
        LoginBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        LoginBtn.setForeground(new java.awt.Color(255, 255, 255));
        LoginBtn.setText("Login");
        LoginBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBtnActionPerformed(evt);
            }
        });
        jPanel2.add(LoginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 360, 42));

        jLabel7.setText("Enter Your Password : ");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));

        cmbRoles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "SuperAdmin" }));
        cmbRoles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbRolesMouseClicked(evt);
            }
        });
        jPanel2.add(cmbRoles, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 190, 30));

        ForgetPass.setBackground(new java.awt.Color(51, 153, 255));
        ForgetPass.setFont(new java.awt.Font("Cascadia Code", 1, 12)); // NOI18N
        ForgetPass.setForeground(new java.awt.Color(255, 51, 51));
        ForgetPass.setText("Forget password!");
        ForgetPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ForgetPassMouseClicked(evt);
            }
        });
        jPanel2.add(ForgetPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, -1, -1));

        changePass.setBackground(new java.awt.Color(51, 153, 255));
        changePass.setFont(new java.awt.Font("Cascadia Code", 1, 12)); // NOI18N
        changePass.setForeground(new java.awt.Color(51, 153, 255));
        changePass.setText("Change password? ");
        changePass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changePassMouseClicked(evt);
            }
        });
        jPanel2.add(changePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, -1, -1));

        ShowPassCheckBox.setText("Show Password");
        ShowPassCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowPassCheckBoxActionPerformed(evt);
            }
        });
        jPanel2.add(ShowPassCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBtnActionPerformed
              // TODO add your handling code here:
              System.exit(0);
    }//GEN-LAST:event_ExitBtnActionPerformed

    
        
    private void LoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBtnActionPerformed
             // TODO add your handling code here:
             
//             frmAdminDashboard frmAdmindash = new frmAdminDashboard();
//             frmAdmindash.setVisible(true);
//             this.dispose();


   if((txtUserName.getText().equals("")) || ( txtPassword.getText().equals("")))
             {
                 JOptionPane.showMessageDialog(this,"Enter Username and Password");
                
             }
 
 
   else {
     
       check();
 
    }
             
             
             
             
             
             
    }//GEN-LAST:event_LoginBtnActionPerformed

    private void cmbRolesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbRolesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbRolesMouseClicked

    private void changePassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changePassMouseClicked
        // TODO add your handling code here:
        frmChangePass frmChangePass = new frmChangePass();
        frmChangePass.setVisible(true);
        dispose();
    }//GEN-LAST:event_changePassMouseClicked

    private void ForgetPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ForgetPassMouseClicked
        // TODO add your handling code here:
        frmForgetPass frmForgetPass = new frmForgetPass();
        frmForgetPass.setVisible(true);
        dispose();
    }//GEN-LAST:event_ForgetPassMouseClicked

    private void ShowPassCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowPassCheckBoxActionPerformed
        // TODO add your handling code here:
        if(ShowPassCheckBox.isSelected()){

            txtPassword.setEchoChar((char)0);
           

        }else{

            txtPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_ShowPassCheckBoxActionPerformed
    
   
       
   public void check() {

    try {

        String uname = txtUserName.getText().trim().toLowerCase();
        String pwd = txtPassword.getText().trim();
        String role =
        cmbRoles.getSelectedItem().toString();

        Connection conn = DatabaseHelper.getConnection();

        String sql = "SELECT * FROM Admins WHERE Email=? AND Password=? AND Role=?";

        PreparedStatement pst = conn.prepareStatement(sql);

        pst.setString(1, uname);
        pst.setString(2, pwd);
        pst.setString(3, role);
        
        System.out.println("Email = " + uname);
        System.out.println("Password = " + pwd);
        System.out.println("Role = " + role);

ResultSet rs = pst.executeQuery();

if(rs.next()){

    String dbRole = rs.getString("Role");
    if(dbRole.equalsIgnoreCase("Admin")){
        
        frmAdminDashboard2.adminName =
                rs.getString("FullName");

        frmAdminDashboard2.adminId =
                rs.getInt("AdminID");

        frmAdminDashboard2.adminEmail =
                rs.getString("Email");

        frmAdminDashboard2.adminRole =
                dbRole;

        frmAdminDashboard2 adminDashboard =
                new frmAdminDashboard2();

        adminDashboard.setVisible(true);

        this.dispose();

    }else if(dbRole.equalsIgnoreCase("SuperAdmin")){
        
        frmSuperAdminDashboard2.adminName =
                rs.getString("FullName");
        frmSuperAdminDashboard2.adminId =
                rs.getInt("AdminID");

        frmSuperAdminDashboard2.adminEmail =
                rs.getString("Email");

        frmSuperAdminDashboard2.adminRole =
                dbRole;

        frmSuperAdminDashboard2 superDashboard =
                new frmSuperAdminDashboard2();

        superDashboard.setVisible(true);

        this.dispose();
    }

}else{

    JOptionPane.showMessageDialog(this,
            "Invalid Email or Password");
}

        rs.close();
        pst.close();
        conn.close();

    } catch (Exception ex) {

        JOptionPane.showMessageDialog(this, ex.getMessage());

    }
}
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new frmLogin().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExitBtn;
    private javax.swing.JLabel ForgetPass;
    private javax.swing.JButton LoginBtn;
    private javax.swing.JCheckBox ShowPassCheckBox;
    private javax.swing.JLabel changePass;
    private javax.swing.JComboBox<String> cmbRoles;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
