/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jusmartlabsystem.FormProblemReport;
import jusmartlabsystem.FormLogin.frmLogin;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jusmartlabsystem.FormDB.DatabaseHelper;
/**
 *
 * @author PC
 */
public class frmStudentReport extends javax.swing.JFrame {

    /**
     * Creates new form frmStudentReport
     */
    public frmStudentReport() {
        initComponents();
        disableFields();
        loadFaculties();
        loadProblemTypes();
        loadServers();
        setLocationRelativeTo(null);
    }
    
    private void disableFields() {

    cmbBatch.setEnabled(false);

    cmbClass.setEnabled(false);

    txtName.setEnabled(false);

    cmbServerNo.setEnabled(false);

    txtComputerNo.setEnabled(false);

    tblStudents.setEnabled(false);
}
    
    private void loadFaculties() {

    try {

        Connection conn =
        DatabaseHelper.getConnection();

        String sql =
        "SELECT FacultyName FROM Faculties";

        PreparedStatement pst =
        conn.prepareStatement(sql);

        ResultSet rs =
        pst.executeQuery();

        cmbFaculty.removeAllItems();

        cmbFaculty.addItem("Select Faculty");

        while(rs.next()) {

            cmbFaculty.addItem(
            rs.getString("FacultyName"));
        }

        conn.close();

    } catch(Exception ex) {

        JOptionPane.showMessageDialog(this,
        ex.getMessage());
    }
}
    private void loadProblemTypes() {

    cmbProblemType.removeAllItems();

    cmbProblemType.addItem("Select Problem");

    cmbProblemType.addItem("System Crash");

    cmbProblemType.addItem("Keyboard Problem");

    cmbProblemType.addItem("Mouse Problem");

    cmbProblemType.addItem("Software Error");

    cmbProblemType.addItem("Network Problem");

    cmbProblemType.addItem("Slow Computer");
}
    private void loadServers() {

    cmbServerNo.removeAllItems();

    cmbServerNo.addItem("Select Server");

    cmbServerNo.addItem("Server 1");

    cmbServerNo.addItem("Server 2");

    cmbServerNo.addItem("Server 3");
}
    
    private void loadBatches() {

    try {

        Connection conn =
        DatabaseHelper.getConnection();

        String sql =
        "SELECT DISTINCT b.BatchName " +
        "FROM Batches b " +
        "JOIN Faculties f " +
        "ON b.FacultyID = f.FacultyID " +
        "WHERE f.FacultyName=?";

        PreparedStatement pst =
        conn.prepareStatement(sql);

        pst.setString(1,
        cmbFaculty.getSelectedItem().toString());

        ResultSet rs =
        pst.executeQuery();

        cmbBatch.removeAllItems();

        cmbBatch.addItem("Select Batch");

        while(rs.next()) {

            cmbBatch.addItem(
            rs.getString("BatchName"));
        }

        conn.close();

    } catch(Exception ex) {

        JOptionPane.showMessageDialog(this,
        ex.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LoginBtn = new javax.swing.JButton();
        ExitBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cmbBatch = new javax.swing.JComboBox<>();
        cmbFaculty = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbClass = new javax.swing.JComboBox<>();
        cmbServerNo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmbProblemType = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtProblemDesc = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        dateChooser = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtComputerNo = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblStudents = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        SubmitBtn = new javax.swing.JButton();
        ClearBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jusmartlabsystem/Resources/feedback1.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        LoginBtn.setBackground(new java.awt.Color(51, 153, 255));
        LoginBtn.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        LoginBtn.setForeground(new java.awt.Color(255, 255, 255));
        LoginBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jusmartlabsystem/Resources/loginAdmins3.png"))); // NOI18N
        LoginBtn.setText("Login");
        LoginBtn.setBorderPainted(false);
        LoginBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LoginBtn.setIconTextGap(10);
        LoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBtnActionPerformed(evt);
            }
        });

        ExitBtn.setBackground(new java.awt.Color(51, 153, 255));
        ExitBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        ExitBtn.setForeground(new java.awt.Color(255, 255, 255));
        ExitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jusmartlabsystem/Resources/closelatest(30).png"))); // NOI18N
        ExitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(ExitBtn)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LoginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(LoginBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(204, 204, 204)
                .addComponent(ExitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Faculty :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 140, -1, -1));

        cmbBatch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmbBatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBatchActionPerformed(evt);
            }
        });
        jPanel2.add(cmbBatch, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 226, 28));

        cmbFaculty.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmbFaculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFacultyActionPerformed(evt);
            }
        });
        jPanel2.add(cmbFaculty, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 226, 28));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Batch :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 178, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Class :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 216, -1, -1));

        cmbClass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmbClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbClassActionPerformed(evt);
            }
        });
        jPanel2.add(cmbClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 226, 28));

        cmbServerNo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmbServerNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbServerNoActionPerformed(evt);
            }
        });
        jPanel2.add(cmbServerNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 226, 28));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Server No :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 298, -1, -1));
        jPanel2.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 226, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Name :");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 254, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Compu No :");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 342, -1, -1));

        cmbProblemType.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(cmbProblemType, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 227, 28));

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Problem Type :");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 382, -1, -1));

        txtProblemDesc.setColumns(20);
        txtProblemDesc.setRows(5);
        jScrollPane1.setViewportView(txtProblemDesc);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, 227, 80));

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Problem Desc :");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 470, -1, -1));

        dateChooser.setMinimumSize(new java.awt.Dimension(50, 22));
        jPanel2.add(dateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 227, 32));

        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Date :");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, -1, -1));

        jLabel2.setFont(new java.awt.Font("Viner Hand ITC", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("S");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 22, -1, -1));

        jLabel12.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("tudent");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 49, -1, -1));

        txtComputerNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtComputerNoFocusLost(evt);
            }
        });
        jPanel2.add(txtComputerNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 226, 30));

        jLabel15.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("roblem");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, -1, -1));

        jLabel16.setFont(new java.awt.Font("Viner Hand ITC", 1, 48)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("P");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        jLabel17.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("ubmission");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, -1, -1));

        jLabel18.setFont(new java.awt.Font("Viner Hand ITC", 1, 48)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("S");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, -1));

        jLabel19.setFont(new java.awt.Font("Viner Hand ITC", 1, 48)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("F");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(523, 22, -1, -1));

        jLabel20.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("orm");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(559, 49, -1, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 84, 700, 2));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jusmartlabsystem/Resources/Student_2.png"))); // NOI18N
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, -1, -1));

        tblStudents.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        tblStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "StudentID", "FullName"
            }
        ));
        tblStudents.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblStudents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblStudentsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblStudents);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, 260, 230));

        SubmitBtn.setBackground(new java.awt.Color(51, 153, 255));
        SubmitBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SubmitBtn.setForeground(new java.awt.Color(255, 255, 255));
        SubmitBtn.setText("Submit");
        SubmitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitBtnActionPerformed(evt);
            }
        });

        ClearBtn.setBackground(new java.awt.Color(51, 153, 255));
        ClearBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ClearBtn.setForeground(new java.awt.Color(255, 255, 255));
        ClearBtn.setText("Clear");
        ClearBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(SubmitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ClearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(286, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SubmitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 700, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbFacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFacultyActionPerformed
        // TODO add your handling code here:
          txtName.setText("");
        if(cmbFaculty.getSelectedIndex() > 0) {

    cmbBatch.setEnabled(true);

    loadBatches();

} else {

    cmbBatch.setEnabled(false);

    cmbClass.setEnabled(false);
}
    }//GEN-LAST:event_cmbFacultyActionPerformed

    
    private void loadClasses() {

    try {

        Connection conn =
        DatabaseHelper.getConnection();

        String sql =
        "SELECT DISTINCT c.ClassName " +
        "FROM Classes c " +
        "JOIN Batches b " +
        "ON c.BatchID = b.BatchID " +
        "JOIN Faculties f " +
        "ON b.FacultyID = f.FacultyID " +
        "WHERE b.BatchName=? " +
        "AND f.FacultyName=?";

        PreparedStatement pst =
        conn.prepareStatement(sql);

        pst.setString(1,
        cmbBatch.getSelectedItem().toString());

        pst.setString(2,
        cmbFaculty.getSelectedItem().toString());

        ResultSet rs =
        pst.executeQuery();

        cmbClass.removeAllItems();

        cmbClass.addItem("Select Class");

        while(rs.next()) {

            cmbClass.addItem(
            rs.getString("ClassName"));
        }

        conn.close();

    } catch(Exception ex) {

        JOptionPane.showMessageDialog(this,
        ex.getMessage());
    }
}
    private void SubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitBtnActionPerformed
        // TODO add your handling code here:
        if(!validateForm()) {

        return;
}
       submitProblem(); 
    }//GEN-LAST:event_SubmitBtnActionPerformed

    private void ClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearBtnActionPerformed
        // TODO add your handling code here:
        // RESET COMBOBOXES
    cmbFaculty.setSelectedIndex(0);

    cmbBatch.removeAllItems();
    cmbBatch.addItem("Select Batch");

    cmbClass.removeAllItems();
    cmbClass.addItem("Select Class");

    cmbServerNo.setSelectedIndex(0);

    cmbProblemType.setSelectedIndex(0);

    // CLEAR TEXTFIELDS
    txtName.setText("");

    txtComputerNo.setText("");

    txtProblemDesc.setText("");

    // CLEAR DATE
    dateChooser.setDate(null);

    // CLEAR TABLE
    DefaultTableModel model =
    (DefaultTableModel) tblStudents.getModel();

    model.setRowCount(0);

    // DISABLE FIELDS AGAIN
    disableFields();

    // FOCUS BACK
    cmbFaculty.requestFocus();
    }//GEN-LAST:event_ClearBtnActionPerformed

    private void LoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBtnActionPerformed
               // TODO add your handling code here:
               frmLogin frmlgn = new frmLogin ();
               frmlgn.setVisible(true);
               this.dispose();
               
    }//GEN-LAST:event_LoginBtnActionPerformed

    private void ExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBtnActionPerformed
        // TODO add your handling code here:
         dispose();
    }//GEN-LAST:event_ExitBtnActionPerformed

    private void cmbServerNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbServerNoActionPerformed
        // TODO add your handling code here:
         if(cmbServerNo.getSelectedIndex() > 0) {

        txtComputerNo.setEnabled(true);

        if(cmbServerNo.getSelectedIndex() == 1) {

            txtComputerNo.setToolTipText(
            "Enter PC Number Between 1 - 28");

        }

        else if(cmbServerNo.getSelectedIndex() == 2) {

            txtComputerNo.setToolTipText(
            "Enter PC Number Between 29 - 56");

        }

        else if(cmbServerNo.getSelectedIndex() == 3) {

            txtComputerNo.setToolTipText(
            "Enter PC Number Between 57 - 84");
        }

        txtComputerNo.requestFocus();

    }

    else {

        txtComputerNo.setEnabled(false);

        txtComputerNo.setText("");
    }

    }//GEN-LAST:event_cmbServerNoActionPerformed

    private void cmbBatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBatchActionPerformed
        // TODO add your handling code here:
          txtName.setText("");
        if(cmbBatch.getSelectedIndex() > 0) {

    cmbClass.setEnabled(true);

    loadClasses();

} else {

    cmbClass.setEnabled(false);
}
    }//GEN-LAST:event_cmbBatchActionPerformed

    
private void loadStudents() {

    try {

        String faculty = cmbFaculty.getSelectedItem().toString();
        String batch = cmbBatch.getSelectedItem().toString();
        String className = cmbClass.getSelectedItem().toString();

        Connection conn = DatabaseHelper.getConnection();

        String sql =
        "SELECT s.StudentID, s.FullName " +
        "FROM Students s " +
        "JOIN Classes c ON s.ClassID = c.ClassID " +
        "JOIN Batches b ON c.BatchID = b.BatchID " +
        "JOIN Faculties f ON b.FacultyID = f.FacultyID " +
        "WHERE f.FacultyName=? " +
        "AND b.BatchName=? " +
        "AND c.ClassName=?";

        PreparedStatement pst = conn.prepareStatement(sql);

        pst.setString(1, faculty);
        pst.setString(2, batch);
        pst.setString(3, className);

        ResultSet rs = pst.executeQuery();

        DefaultTableModel model =
        (DefaultTableModel) tblStudents.getModel();

        model.setRowCount(0);

        while (rs.next()) {

            model.addRow(new Object[]{
                rs.getInt("StudentID"),
                rs.getString("FullName")
            });
        }

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this, e);

    }
}
    private void cmbClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbClassActionPerformed
        // TODO add your handling code here:
          txtName.setText("");
        if(cmbClass.getSelectedIndex() > 0) {

    txtName.setEnabled(true);

    cmbServerNo.setEnabled(true);

    tblStudents.setEnabled(true);

    loadStudents();
}
    }//GEN-LAST:event_cmbClassActionPerformed

    private void tblStudentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStudentsMouseClicked
        // TODO add your handling code here:
        int row = tblStudents.getSelectedRow();
        txtName.setText(
        tblStudents.getValueAt(row, 1).toString());
    }//GEN-LAST:event_tblStudentsMouseClicked

    private void txtComputerNoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtComputerNoFocusLost
        // TODO add your handling code here:
        
          String text =
    txtComputerNo.getText().trim();

    // EMPTY
    if(text.isEmpty()) {

        return;
    }

    // REMOVE EXISTING PC
    text = text.replace("PC", "");
    text = text.replace("pc", "");
    text = text.trim();

    try {

        int number =
        Integer.parseInt(text);

        // AUTO ADD PREFIX
        txtComputerNo.setText(
        "PC " + number);

    }

    catch(Exception e) {

        JOptionPane.showMessageDialog(this,
        "Invalid PC Number");
    }
    }//GEN-LAST:event_txtComputerNoFocusLost

    
    private boolean validateForm() {

    // Faculty Validation
    
    if(cmbFaculty.getSelectedIndex() == 0) {

        JOptionPane.showMessageDialog(this,
        "Please Select Faculty");

        cmbFaculty.requestFocus();

        return false;
    }

    // Batch Validation
    if(cmbBatch.getSelectedIndex() == 0) {

        JOptionPane.showMessageDialog(this,
        "Please Select Batch");

        cmbBatch.requestFocus();

        return false;
    }

    // Class Validation
    if(cmbClass.getSelectedIndex() == 0) {

        JOptionPane.showMessageDialog(this,
        "Please Select Class");

        cmbClass.requestFocus();

        return false;
    }

    // Student Validation
    if(txtName.getText().trim().isEmpty()) {

        JOptionPane.showMessageDialog(this,
        "Please Select Student");

        txtName.requestFocus();

        return false;
    }
    String enteredName =
txtName.getText().trim();

boolean studentFound = false;

for(int i = 0; i < tblStudents.getRowCount(); i++) {

    String tableName =
    tblStudents.getValueAt(i, 1).toString();

    if(tableName.equalsIgnoreCase(enteredName)) {

        studentFound = true;
        break;
    }
}

if(!studentFound) {

    JOptionPane.showMessageDialog(this,
    "You are not registered student");

    txtName.requestFocus();

    return false;
}

    // SERVER VALIDATION
    if(cmbServerNo.getSelectedIndex() == 0) {

        JOptionPane.showMessageDialog(this,
        "Please Select Server");

        cmbServerNo.requestFocus();

        return false;
    }

    // PC VALIDATION
    if(txtComputerNo.getText().trim().isEmpty()) {

        JOptionPane.showMessageDialog(this,
        "Please Enter Computer Number");

        txtComputerNo.requestFocus();

        return false;
    }

    // GET PC NUMBER
    String pcText =
    txtComputerNo.getText().trim();

    pcText = pcText.replace("PC", "");
    pcText = pcText.replace("pc", "");
    pcText = pcText.trim();

    int pcNo;

    try {

        pcNo = Integer.parseInt(pcText);

    } catch(Exception e) {

        JOptionPane.showMessageDialog(this,
        "Invalid PC Number");

        txtComputerNo.requestFocus();

        return false;
    }

    // SERVER RANGE VALIDATION
    int server =
    cmbServerNo.getSelectedIndex();

    boolean valid = false;

    // SERVER 1
    if(server == 1) {

        if(pcNo >= 1 && pcNo <= 28) {

            valid = true;
        }
    }

    // SERVER 2
    else if(server == 2) {

        if(pcNo >= 29 && pcNo <= 56) {

            valid = true;
        }
    }

    // SERVER 3
    else if(server == 3) {

        if(pcNo >= 57 && pcNo <= 84) {

            valid = true;
        }
    }

    // INVALID RANGE
    if(!valid) {

        JOptionPane.showMessageDialog(this,
        "PC Number does not belong to selected Server");

        txtComputerNo.requestFocus();

        return false;
    }

    // PROBLEM TYPE VALIDATION
    if(cmbProblemType.getSelectedIndex() == 0) {

        JOptionPane.showMessageDialog(this,
        "Please Select Problem Type");

        cmbProblemType.requestFocus();

        return false;
    }

    return true;
}
    
    private void submitProblem() {

    try {

        Connection conn =
        DatabaseHelper.getConnection();

        // GET STUDENT ID
        int studentID = 0;

        for(int i = 0; i < tblStudents.getRowCount(); i++) {

            String name =
            tblStudents.getValueAt(i, 1).toString();

            if(name.equalsIgnoreCase(
            txtName.getText().trim())) {

                studentID =
                Integer.parseInt(
                tblStudents.getValueAt(i, 0).toString());

                break;
            }
        }

        String sql =
        "INSERT INTO problemreports " +
        "(ProblemType, ProblemDescription, StudentID, ComputerNumber, ServerNo) " +
        "VALUES (?, ?, ?, ?, ?)";

        PreparedStatement pst =
        conn.prepareStatement(sql);

        pst.setString(1,
        cmbProblemType.getSelectedItem().toString());

        pst.setString(2,
        txtProblemDesc.getText());

        pst.setInt(3,
        studentID);

        pst.setString(4,
        txtComputerNo.getText());

        String serverText =
        cmbServerNo.getSelectedItem().toString();

        serverText =
        serverText.replace("Server", "").trim();

        pst.setInt(5,
        Integer.parseInt(serverText));

        pst.executeUpdate();

        JOptionPane.showMessageDialog(this,
        "Problem Submitted Successfully");

        conn.close();

    }

    catch (Exception e) {

        javax.swing.JOptionPane.showMessageDialog(this, e);

    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmStudentReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmStudentReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmStudentReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmStudentReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new frmStudentReport().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClearBtn;
    private javax.swing.JButton ExitBtn;
    private javax.swing.JButton LoginBtn;
    private javax.swing.JButton SubmitBtn;
    private javax.swing.JComboBox<String> cmbBatch;
    private javax.swing.JComboBox<String> cmbClass;
    private javax.swing.JComboBox<String> cmbFaculty;
    private javax.swing.JComboBox<String> cmbProblemType;
    private javax.swing.JComboBox<String> cmbServerNo;
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblStudents;
    private javax.swing.JTextField txtComputerNo;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextArea txtProblemDesc;
    // End of variables declaration//GEN-END:variables
}
