/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jusmartlabsystem.SuperAdminDash;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import jusmartlabsystem.FormLogin.frmLogin;
import jusmartlabsystem.FormDB.DatabaseHelper;

/**
 *
 * @author PC
 */
public class frmSuperAdminProfile extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmSuperAdminDashboard2.class.getName());
    
    

    /**
     * Creates new form frmAdminDashboard2
     */
    public frmSuperAdminProfile() {
        initComponents();
        AdminProfileBtn.setBackground(new java.awt.Color(51,51,51));
        loadAdminProfile();
        if(frmSuperAdminDashboard2.darkMode){
        applyDarkMode();

       }
        txtAdminName.setEditable(false);
        txtAdminEmail.setEditable(false);
        txtAdminRole.setEditable(false);
        txtName3.setEditable(false);
        BtnLogout.setFocusPainted(false);
        BtnLogout.setBorderPainted(false);
        BtnLogout.setFocusable(false);
    }
    
    private void loadAdminProfile(){

    try{

        Connection con = DatabaseHelper.getConnection();

        String sql =
        "SELECT * FROM admins WHERE AdminID=?";

        PreparedStatement pst =
        con.prepareStatement(sql);

        pst.setInt(
        1,
        frmSuperAdminDashboard2.adminId
        );

        ResultSet rs = pst.executeQuery();

        if(rs.next()){

            txtAdminName.setText(
            rs.getString("FullName"));

            txtAdminEmail.setText(
            rs.getString("Email"));

            txtAdminRole.setText(
            rs.getString("Role"));

            txtName3.setText(
            rs.getString("CreatedAt"));

        }

    }

    catch(Exception e){

        javax.swing.JOptionPane.showMessageDialog(this, e);

    }

}private void applyDarkMode(){

    DashboardContents2.setBackground(
    new java.awt.Color(30,30,30));

    jPanel1.setBackground(
    new java.awt.Color(20,20,20));

    DashboardAdminBtn.setBackground(
    new java.awt.Color(45,45,45));

    ManageReportAdminBtn.setBackground(
    new java.awt.Color(45,45,45));

    AdminProfileBtn.setBackground(
    new java.awt.Color(45,45,45));

    ChangeProfileBtn.setBackground(
    new java.awt.Color(45,45,45));

}
    
    private void applyLightMode(){

    DashboardContents2.setBackground(
    java.awt.Color.WHITE);

    jPanel1.setBackground(
    new java.awt.Color(51,153,255));

    DashboardAdminBtn.setBackground(
    new java.awt.Color(51,153,255));

    ManageReportAdminBtn.setBackground(
    new java.awt.Color(51,153,255));

    AdminProfileBtn.setBackground(
    new java.awt.Color(51,153,255));

    ChangeProfileBtn.setBackground(
    new java.awt.Color(51,153,255));

}
    private void resetButtonColors() {

    DashboardAdminBtn.setBackground(new java.awt.Color(51,153,255));
    ManageReportAdminBtn.setBackground(new java.awt.Color(51,153,255));
    AdminProfileBtn.setBackground(new java.awt.Color(51,153,255));
    ChangeProfileBtn.setBackground(new java.awt.Color(51,153,255));

}
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        DashboardAdminBtn = new javax.swing.JButton();
        ManageReportAdminBtn = new javax.swing.JButton();
        AdminProfileBtn = new javax.swing.JButton();
        ChangeProfileBtn = new javax.swing.JButton();
        DashboardContents2 = new javax.swing.JPanel();
        ExitBtn = new javax.swing.JButton();
        profilePanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtAdminName = new javax.swing.JTextField();
        txtAdminEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtAdminRole = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtName3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        BtnLogout = new javax.swing.JButton();
        btnDarkMode = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1922, 1030));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 153, -1, -1));

        DashboardAdminBtn.setBackground(new java.awt.Color(51, 153, 255));
        DashboardAdminBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        DashboardAdminBtn.setForeground(new java.awt.Color(255, 255, 255));
        DashboardAdminBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jusmartlabsystem/Resources/home (4).png"))); // NOI18N
        DashboardAdminBtn.setText("Dashboard        ");
        DashboardAdminBtn.setActionCommand("Dashboard........");
        DashboardAdminBtn.setBorder(null);
        DashboardAdminBtn.setContentAreaFilled(false);
        DashboardAdminBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DashboardAdminBtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        DashboardAdminBtn.setIconTextGap(10);
        DashboardAdminBtn.addActionListener(this::DashboardAdminBtnActionPerformed);
        jPanel1.add(DashboardAdminBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 31, 180, 40));

        ManageReportAdminBtn.setBackground(new java.awt.Color(51, 153, 255));
        ManageReportAdminBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ManageReportAdminBtn.setForeground(new java.awt.Color(255, 255, 255));
        ManageReportAdminBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jusmartlabsystem/Resources/document.png"))); // NOI18N
        ManageReportAdminBtn.setText("Manage Report");
        ManageReportAdminBtn.setBorder(null);
        ManageReportAdminBtn.setContentAreaFilled(false);
        ManageReportAdminBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ManageReportAdminBtn.addActionListener(this::ManageReportAdminBtnActionPerformed);
        jPanel1.add(ManageReportAdminBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 77, 180, 40));

        AdminProfileBtn.setBackground(new java.awt.Color(51, 153, 255));
        AdminProfileBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        AdminProfileBtn.setForeground(new java.awt.Color(255, 255, 255));
        AdminProfileBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jusmartlabsystem/Resources/user.png"))); // NOI18N
        AdminProfileBtn.setText("Admin Profile    ");
        AdminProfileBtn.setBorder(null);
        AdminProfileBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AdminProfileBtn.addActionListener(this::AdminProfileBtnActionPerformed);
        jPanel1.add(AdminProfileBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 129, 180, 40));

        ChangeProfileBtn.setBackground(new java.awt.Color(51, 153, 255));
        ChangeProfileBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ChangeProfileBtn.setForeground(new java.awt.Color(255, 255, 255));
        ChangeProfileBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jusmartlabsystem/Resources/change.png"))); // NOI18N
        ChangeProfileBtn.setText("Change Profile   ");
        ChangeProfileBtn.setToolTipText("");
        ChangeProfileBtn.setBorder(null);
        ChangeProfileBtn.setContentAreaFilled(false);
        ChangeProfileBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ChangeProfileBtn.addActionListener(this::ChangeProfileBtnActionPerformed);
        jPanel1.add(ChangeProfileBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 175, 180, 40));

        DashboardContents2.setBackground(new java.awt.Color(255, 255, 255));
        DashboardContents2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ExitBtn.setBackground(new java.awt.Color(51, 153, 255));
        ExitBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        ExitBtn.setForeground(new java.awt.Color(255, 255, 255));
        ExitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jusmartlabsystem/Resources/closelatest(30).png"))); // NOI18N
        ExitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ExitBtn.addActionListener(this::ExitBtnActionPerformed);
        DashboardContents2.add(ExitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 10, 50, 30));

        profilePanel.setBackground(new java.awt.Color(51, 153, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1.setText("Admin Profile Information");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(182, 182, 182))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(14, 14, 14))
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel2)
                .addContainerGap(615, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Name :");

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Email :");

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Role :");

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Account Created :");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jusmartlabsystem/Resources/information.png"))); // NOI18N
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 661, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout profilePanelLayout = new javax.swing.GroupLayout(profilePanel);
        profilePanel.setLayout(profilePanelLayout);
        profilePanelLayout.setHorizontalGroup(
            profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(profilePanelLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profilePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profilePanelLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(316, 316, 316))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profilePanelLayout.createSequentialGroup()
                        .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(profilePanelLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAdminName, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(profilePanelLayout.createSequentialGroup()
                                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(6, 6, 6)
                                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtName3, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAdminRole, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAdminEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(136, 136, 136))))
            .addGroup(profilePanelLayout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        profilePanelLayout.setVerticalGroup(
            profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel11)
                .addGap(31, 31, 31)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtAdminName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAdminEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAdminRole, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addContainerGap(108, Short.MAX_VALUE))
        );

        DashboardContents2.add(profilePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 660, 410));

        jPanel7.setBackground(new java.awt.Color(51, 153, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 70, Short.MAX_VALUE))
        );

        DashboardContents2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 10, 70));

        jPanel9.setBackground(new java.awt.Color(51, 153, 255));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(0, 70, Short.MAX_VALUE))
        );

        DashboardContents2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 60, 10, 70));

        jPanel10.setBackground(new java.awt.Color(51, 153, 255));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(0, 340, Short.MAX_VALUE))
        );

        DashboardContents2.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 130, 10, 340));

        jPanel8.setBackground(new java.awt.Color(51, 153, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(0, 340, Short.MAX_VALUE))
        );

        DashboardContents2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 10, -1));

        BtnLogout.setBackground(new java.awt.Color(51, 153, 255));
        BtnLogout.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        BtnLogout.setForeground(new java.awt.Color(255, 255, 255));
        BtnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jusmartlabsystem/Resources/logout (2).png"))); // NOI18N
        BtnLogout.setText("Logout");
        BtnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnLogout.addActionListener(this::BtnLogoutActionPerformed);
        DashboardContents2.add(BtnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, 100, 30));

        btnDarkMode.setBackground(new java.awt.Color(51, 153, 255));
        btnDarkMode.setForeground(new java.awt.Color(255, 255, 255));
        btnDarkMode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jusmartlabsystem/Resources/user-interface(theme).png"))); // NOI18N
        btnDarkMode.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDarkMode.addActionListener(this::btnDarkModeActionPerformed);
        DashboardContents2.add(btnDarkMode, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 10, 50, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(DashboardContents2, javax.swing.GroupLayout.PREFERRED_SIZE, 1667, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1030, Short.MAX_VALUE)
            .addComponent(DashboardContents2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DashboardAdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DashboardAdminBtnActionPerformed
        // TODO add your handling code here:
        resetButtonColors();
        DashboardAdminBtn.setBackground(new java.awt.Color(51,51,51));
        frmSuperAdminDashboard2 frmAdminDashboard2 = new frmSuperAdminDashboard2();
        frmAdminDashboard2.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_DashboardAdminBtnActionPerformed

    private void ManageReportAdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageReportAdminBtnActionPerformed
        // TODO add your handling code here:
        resetButtonColors();
        ManageReportAdminBtn.setBackground(new java.awt.Color(51,51,51));
        ManageReportsSuperadmin MngReportamdn = new ManageReportsSuperadmin();
        MngReportamdn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ManageReportAdminBtnActionPerformed

    private void AdminProfileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminProfileBtnActionPerformed
        // TODO add your handling code here:
        resetButtonColors();
        AdminProfileBtn.setBackground(new java.awt.Color(51,51,51));
        frmSuperAdminProfile frmAdminProfile = new frmSuperAdminProfile();
        frmAdminProfile.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AdminProfileBtnActionPerformed

    private void ChangeProfileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeProfileBtnActionPerformed
        // TODO add your handling code here:
        resetButtonColors();
        ChangeProfileBtn.setBackground(new java.awt.Color(51,51,51));
        frmSuperAdminChangeProfile frmAdminChangeProfile = new frmSuperAdminChangeProfile();
        frmAdminChangeProfile.setVisible(true);
        this.dispose();
        
        
    }//GEN-LAST:event_ChangeProfileBtnActionPerformed

    private void ExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBtnActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_ExitBtnActionPerformed

    private void BtnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLogoutActionPerformed
        // TODO add your handling code here:
        int choice = javax.swing.JOptionPane.showConfirmDialog(
        profilePanel,
        "Are you sure you want to logout?",
        "Logout",
        javax.swing.JOptionPane.YES_NO_OPTION
        );

        if(choice == javax.swing.JOptionPane.YES_OPTION){

            frmSuperAdminDashboard2.adminId = 0;
            frmSuperAdminDashboard2.adminRole = null;
            frmSuperAdminDashboard2.adminEmail = null;

            frmLogin login = new frmLogin();
            login.setVisible(true);

            this.dispose();

    }
    }//GEN-LAST:event_BtnLogoutActionPerformed

    private void btnDarkModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDarkModeActionPerformed
        // TODO add your handling code here:
        if(frmSuperAdminDashboard2.darkMode == false){

        frmSuperAdminDashboard2.darkMode = true;

        applyDarkMode();

    }

    else{

        frmSuperAdminDashboard2.darkMode = false;

        applyLightMode();

    }
    }//GEN-LAST:event_btnDarkModeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
      java.awt.EventQueue.invokeLater(() -> new frmSuperAdminChangeProfile().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminProfileBtn;
    private javax.swing.JButton BtnLogout;
    private javax.swing.JButton ChangeProfileBtn;
    private javax.swing.JButton DashboardAdminBtn;
    private javax.swing.JPanel DashboardContents2;
    private javax.swing.JButton ExitBtn;
    private javax.swing.JButton ManageReportAdminBtn;
    private javax.swing.JButton btnDarkMode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel profilePanel;
    private javax.swing.JTextField txtAdminEmail;
    private javax.swing.JTextField txtAdminName;
    private javax.swing.JTextField txtAdminRole;
    private javax.swing.JTextField txtName3;
    // End of variables declaration//GEN-END:variables
}
