/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jusmartlabsystem.AdminDash;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import jusmartlabsystem.FormDB.DatabaseHelper;

/**
 *
 * @author PC
 */
public class frmAdminDashboard2 extends javax.swing.JFrame {
    
    public static int adminId;
    public static String adminRole;
    public static String adminEmail;
    public static String adminName;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmAdminDashboard2.class.getName());
    public static boolean darkMode = false;
    
    

    /**
     * Creates new form frmAdminDashboard2
     */
    public frmAdminDashboard2() {
        initComponents();
         lblWelcome.setText(
            adminName + " (" + adminRole + ")"
    );
        DashboardAdminBtn.setBackground(new java.awt.Color(51,51,51));
        loadDashboardCounts();
        if(frmAdminDashboard2.darkMode){
        applyDarkMode();

   }
    }
    
    private void resetButtonColors() {

    DashboardAdminBtn.setBackground(new java.awt.Color(51,51,51));
    ManageReportAdminBtn.setBackground(new java.awt.Color(51,153,255));
    AdminProfileBtn.setBackground(new java.awt.Color(51,153,255));
    ChangeProfileBtn.setBackground(new java.awt.Color(51,153,255));

}
    
    private void applyDarkMode(){

    DashboardContents2.setBackground(
    new java.awt.Color(30,30,30));

    jPanel1.setBackground(
    new java.awt.Color(20,20,20));

    DashboardAdminBtn.setBackground(
    new java.awt.Color(45,45,45));

    ManageReportAdminBtn.setBackground(
    new java.awt.Color(45,45,45));

    AdminProfileBtn.setBackground(
    new java.awt.Color(45,45,45));

    ChangeProfileBtn.setBackground(
    new java.awt.Color(45,45,45));

}
    
    private void applyLightMode(){

    DashboardContents2.setBackground(
    java.awt.Color.WHITE);

    jPanel1.setBackground(
    new java.awt.Color(51,153,255));

    DashboardAdminBtn.setBackground(
    new java.awt.Color(51,153,255));

    ManageReportAdminBtn.setBackground(
    new java.awt.Color(51,153,255));

    AdminProfileBtn.setBackground(
    new java.awt.Color(51,153,255));

    ChangeProfileBtn.setBackground(
    new java.awt.Color(51,153,255));

}
    
    private void loadDashboardCounts() {

    try {

        Connection con = DatabaseHelper.getConnection();

        // TOTAL REPORTS
        String totalQuery =
        "SELECT COUNT(*) FROM problemreports";

        PreparedStatement pst1 =
        con.prepareStatement(totalQuery);

        ResultSet rs1 = pst1.executeQuery();

        if (rs1.next()) {

            lblTotalReport.setText(rs1.getString(1));

        }

        // TOTAL PENDING
        String pendingQuery =
        "SELECT COUNT(*) FROM problemreports WHERE Status='Pending'";

        PreparedStatement pst2 =
        con.prepareStatement(pendingQuery);

        ResultSet rs2 = pst2.executeQuery();

        if (rs2.next()) {

            lblTotalPending.setText(rs2.getString(1));

        }

        // TOTAL FIXED
        String fixedQuery =
        "SELECT COUNT(*) FROM problemreports WHERE Status='Fixed'";

        PreparedStatement pst3 =
        con.prepareStatement(fixedQuery);

        ResultSet rs3 = pst3.executeQuery();

        if (rs3.next()) {

            lblTotalFixed.setText(rs3.getString(1));

        }

    } catch (Exception e) {

        javax.swing.JOptionPane.showMessageDialog(this, e);

    }

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        DashboardAdminBtn = new javax.swing.JButton();
        ManageReportAdminBtn = new javax.swing.JButton();
        AdminProfileBtn = new javax.swing.JButton();
        ChangeProfileBtn = new javax.swing.JButton();
        DashboardContents2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        lblTotalPending = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        lblTotalFixed = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jPanel19 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        lblTotalReport = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        ExitBtn = new javax.swing.JButton();
        btnDarkMode = new javax.swing.JButton();
        lblWelcome = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 153, -1, -1));

        DashboardAdminBtn.setBackground(new java.awt.Color(51, 153, 255));
        DashboardAdminBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        DashboardAdminBtn.setForeground(new java.awt.Color(255, 255, 255));
        DashboardAdminBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jusmartlabsystem/Resources/home (4).png"))); // NOI18N
        DashboardAdminBtn.setText("Dashboard        ");
        DashboardAdminBtn.setActionCommand("Dashboard........");
        DashboardAdminBtn.setBorderPainted(false);
        DashboardAdminBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DashboardAdminBtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        DashboardAdminBtn.setIconTextGap(10);
        DashboardAdminBtn.addActionListener(this::DashboardAdminBtnActionPerformed);
        jPanel1.add(DashboardAdminBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 31, 180, 40));

        ManageReportAdminBtn.setBackground(new java.awt.Color(51, 153, 255));
        ManageReportAdminBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ManageReportAdminBtn.setForeground(new java.awt.Color(255, 255, 255));
        ManageReportAdminBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jusmartlabsystem/Resources/document.png"))); // NOI18N
        ManageReportAdminBtn.setText("Manage Report");
        ManageReportAdminBtn.setBorder(null);
        ManageReportAdminBtn.setBorderPainted(false);
        ManageReportAdminBtn.setContentAreaFilled(false);
        ManageReportAdminBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ManageReportAdminBtn.addActionListener(this::ManageReportAdminBtnActionPerformed);
        jPanel1.add(ManageReportAdminBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 77, 180, 40));

        AdminProfileBtn.setBackground(new java.awt.Color(51, 153, 255));
        AdminProfileBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        AdminProfileBtn.setForeground(new java.awt.Color(255, 255, 255));
        AdminProfileBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jusmartlabsystem/Resources/user.png"))); // NOI18N
        AdminProfileBtn.setText("Admin Profile    ");
        AdminProfileBtn.setBorder(null);
        AdminProfileBtn.setBorderPainted(false);
        AdminProfileBtn.setContentAreaFilled(false);
        AdminProfileBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AdminProfileBtn.addActionListener(this::AdminProfileBtnActionPerformed);
        jPanel1.add(AdminProfileBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 129, 180, 40));

        ChangeProfileBtn.setBackground(new java.awt.Color(51, 153, 255));
        ChangeProfileBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ChangeProfileBtn.setForeground(new java.awt.Color(255, 255, 255));
        ChangeProfileBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jusmartlabsystem/Resources/change.png"))); // NOI18N
        ChangeProfileBtn.setText("Change Profile   ");
        ChangeProfileBtn.setToolTipText("");
        ChangeProfileBtn.setBorder(null);
        ChangeProfileBtn.setBorderPainted(false);
        ChangeProfileBtn.setContentAreaFilled(false);
        ChangeProfileBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ChangeProfileBtn.addActionListener(this::ChangeProfileBtnActionPerformed);
        jPanel1.add(ChangeProfileBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 175, 180, 40));

        DashboardContents2.setBackground(new java.awt.Color(255, 255, 255));
        DashboardContents2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(51, 153, 255));

        jPanel10.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        lblTotalPending.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblTotalPending.setForeground(new java.awt.Color(255, 255, 255));
        lblTotalPending.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jusmartlabsystem/Resources/loading.png"))); // NOI18N
        lblTotalPending.setText("0");
        lblTotalPending.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Total Pending");

        jButton6.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(lblTotalPending, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 39, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(lblTotalPending)
                .addGap(31, 31, 31)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        DashboardContents2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 160, 110));

        jPanel11.setBackground(new java.awt.Color(51, 153, 255));

        jPanel12.setBackground(new java.awt.Color(51, 255, 0));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        lblTotalFixed.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblTotalFixed.setForeground(new java.awt.Color(255, 255, 255));
        lblTotalFixed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jusmartlabsystem/Resources/checked.png"))); // NOI18N
        lblTotalFixed.setText("0");
        lblTotalFixed.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Total fixed");

        jButton7.setBackground(new java.awt.Color(51, 255, 0));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(lblTotalFixed, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTotalFixed)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        DashboardContents2.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 160, 110));

        jPanel19.setBackground(new java.awt.Color(51, 153, 255));

        jPanel18.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        lblTotalReport.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblTotalReport.setForeground(new java.awt.Color(255, 255, 255));
        lblTotalReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jusmartlabsystem/Resources/document.png"))); // NOI18N
        lblTotalReport.setText("0");
        lblTotalReport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Total Report");

        jButton5.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                        .addComponent(lblTotalReport, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTotalReport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        DashboardContents2.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 70, 160, 110));

        ExitBtn.setBackground(new java.awt.Color(51, 153, 255));
        ExitBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        ExitBtn.setForeground(new java.awt.Color(255, 255, 255));
        ExitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jusmartlabsystem/Resources/closelatest(30).png"))); // NOI18N
        ExitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ExitBtn.addActionListener(this::ExitBtnActionPerformed);
        DashboardContents2.add(ExitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 10, 50, 30));

        btnDarkMode.setBackground(new java.awt.Color(51, 153, 255));
        btnDarkMode.setForeground(new java.awt.Color(255, 255, 255));
        btnDarkMode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jusmartlabsystem/Resources/user-interface(theme).png"))); // NOI18N
        btnDarkMode.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDarkMode.addActionListener(this::btnDarkModeActionPerformed);
        DashboardContents2.add(btnDarkMode, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 10, 50, 30));

        lblWelcome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(51, 153, 255));
        DashboardContents2.add(lblWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        jLabel3.setText("Welcome ");
        DashboardContents2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(DashboardContents2, javax.swing.GroupLayout.DEFAULT_SIZE, 1740, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DashboardContents2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1030, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DashboardAdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DashboardAdminBtnActionPerformed
        // TODO add your handling code here:
        resetButtonColors();
        DashboardAdminBtn.setBackground(new java.awt.Color(51,51,51));
        frmAdminDashboard2 frmAdminDashboard2 = new frmAdminDashboard2();
        frmAdminDashboard2.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_DashboardAdminBtnActionPerformed

    private void ManageReportAdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageReportAdminBtnActionPerformed
        // TODO add your handling code here:
        resetButtonColors();
        ManageReportAdminBtn.setBackground(new java.awt.Color(51,51,51));
        ManageReportsAdmin MngReportamdn = new ManageReportsAdmin();
        MngReportamdn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ManageReportAdminBtnActionPerformed

    private void AdminProfileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminProfileBtnActionPerformed
        // TODO add your handling code here:
        resetButtonColors();
        AdminProfileBtn.setBackground(new java.awt.Color(51,51,51));
        frmAdminProfile frmAdminProfile = new frmAdminProfile();
        frmAdminProfile.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_AdminProfileBtnActionPerformed

    private void ChangeProfileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeProfileBtnActionPerformed
        // TODO add your handling code here:
        resetButtonColors();
        ChangeProfileBtn.setBackground(new java.awt.Color(51,51,51));
        frmAdminChangeProfile frmAdminChangeProfile = new  frmAdminChangeProfile();
        frmAdminChangeProfile.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_ChangeProfileBtnActionPerformed

    private void ExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBtnActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_ExitBtnActionPerformed

    private void btnDarkModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDarkModeActionPerformed
        // TODO add your handling code here:
        if(frmAdminDashboard2.darkMode == false){

        frmAdminDashboard2.darkMode = true;

        applyDarkMode();

    }

    else{

        frmAdminDashboard2.darkMode = false;

        applyLightMode();

    }
    }//GEN-LAST:event_btnDarkModeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmAdminDashboard2().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminProfileBtn;
    private javax.swing.JButton ChangeProfileBtn;
    private javax.swing.JButton DashboardAdminBtn;
    private javax.swing.JPanel DashboardContents2;
    private javax.swing.JButton ExitBtn;
    private javax.swing.JButton ManageReportAdminBtn;
    private javax.swing.JButton btnDarkMode;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lblTotalFixed;
    private javax.swing.JLabel lblTotalPending;
    private javax.swing.JLabel lblTotalReport;
    private javax.swing.JLabel lblWelcome;
    // End of variables declaration//GEN-END:variables
}
